name: Cypress Tests

on: [push,pull_request]

jobs:

  test-cypress:
    name: itk-wasm browser tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.16'

      - name: Install
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Test with Chrome
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run test:chrome

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      #- name: Test with Firefox
        #uses: cypress-io/github-action@v6
        #with:
          #browser: firefox
          #command: npm run test:firefox

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
