name: Examples

on: [push,pull_request]

jobs:
  test-node-example:
    name: node-js
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./examples/node-js

    steps:
    - uses: actions/checkout@v3

    - name: 'Free up disk space'
      run: |
        # Workaround for https://github.com/actions/virtual-environments/issues/709
        df -h
        sudo apt-get update
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf /usr/share/dotnet/
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install
      run: |
        npm install

    - name: Test
      run: |
        npm run test

  build-hello-world-example:
    name: hello-world build
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./examples/hello-world

    steps:
    - uses: actions/checkout@v3

    - name: 'Free up disk space'
      run: |
        # Workaround for https://github.com/actions/virtual-environments/issues/709
        df -h
        sudo apt-get update
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf /usr/share/dotnet/
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install
      run: |
        npm install

    - name: Build
      run: |
        npm run build

    - name: Save wasm builds
      uses: actions/upload-artifact@v3
      with:
        name: hello-world-build
        if-no-files-found: error
        path: |
          examples/hello-world/emscripten-build
          examples/hello-world/wasi-build


  test-hello-world-example:
    name: hello-world test
    needs: build-hello-world-example
    runs-on: ubuntu-22.04
    container: cypress/browsers:node18.12.0-chrome107

    defaults:
      run:
        working-directory: ./examples/hello-world

    steps:
    - uses: actions/checkout@v3

    - name: Load wasm builds
      uses: actions/download-artifact@v3
      with:
        name: hello-world-build
        path: examples/hello-world

    - name: Test
      uses: cypress-io/github-action@v6
      with:
        working-directory: ./examples/hello-world
        browser: chrome
        start: npm start

  build-test-hello-pipeline-example:
    name: hello-pipeline build test
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./examples/hello-pipeline

    steps:
    - uses: actions/checkout@v3

    - name: 'Free up disk space'
      run: |
        # Workaround for https://github.com/actions/virtual-environments/issues/709
        df -h
        sudo apt-get update
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf /usr/share/dotnet/
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install
      run: |
        npm install

    - name: Build
      run: |
        npm run build

    - name: Test
      run: |
        npm run test
        npm run test:quiet
        npm run test:help

  build-test-inputs-outputs-example:
    name: inputs-outputs
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./examples/inputs-outputs

    steps:
    - uses: actions/checkout@v3

    - name: 'Free up disk space'
      run: |
        # Workaround for https://github.com/actions/virtual-environments/issues/709
        df -h
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf /usr/share/dotnet/
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install
      run: |
        npm install

    - name: Build
      run: |
        npm run build

    - name: Test
      run: |
        npm run test

  test-umd-example:
    name: umd
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: 'Free up disk space'
      run: |
        # Workaround for https://github.com/actions/virtual-environments/issues/709
        df -h
        sudo apt-get update
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf /usr/share/dotnet/
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - name: Test
      uses: cypress-io/github-action@v6
      with:
        working-directory: ./examples/umd
        browser: chrome
        start: npm start

  test-webpack-example:
    name: webpack
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: 'Free up disk space'
      run: |
        # Workaround for https://github.com/actions/virtual-environments/issues/709
        df -h
        sudo apt-get update
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf /usr/share/dotnet/
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - name: Test Webpack Example on Chrome
      uses: cypress-io/github-action@v6
      with:
        working-directory: ./examples/webpack
        browser: chrome
        start: npm start

    #- name: Test Webpack Example on Firefox
      #uses: cypress-io/github-action@v6
      #with:
        #working-directory: ./examples/webpack
        #browser: firefox
        #start: npm start

  test-vite-example:
    name: vite
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: 'Free up disk space'
      run: |
        # Workaround for https://github.com/actions/virtual-environments/issues/709
        df -h
        sudo apt-get update
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf /usr/share/dotnet/
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - name: Test Vite Example on Chrome
      uses: cypress-io/github-action@v6
      with:
        working-directory: ./examples/vite
        browser: chrome
        start: npm start

    #- name: Test Vite Example on Firefox
      #uses: cypress-io/github-action@v6
      #with:
        #working-directory: ./examples/vite
        #browser: firefox
        #start: npm start

  test-debugging-example:
    name: debugging
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./examples/debugging

    steps:
    - uses: actions/checkout@v3

    - name: 'Free up disk space'
      run: |
        # Workaround for https://github.com/actions/virtual-environments/issues/709
        df -h
        sudo apt-get update
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf /usr/share/dotnet/
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install
      run: |
        npm install

    - name: Build
      run: |
        npm run native-build
        npm run emscripten-build-release
        npm run emscripten-build-debug
        npm run wasi-build-debug

  test-different-input-types-example:
    name: different-input-types
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./examples/different-input-types

    steps:
    - uses: actions/checkout@v3

    - name: 'Free up disk space'
      run: |
        # Workaround for https://github.com/actions/virtual-environments/issues/709
        df -h
        sudo apt-get update
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf /usr/share/dotnet/
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install
      run: |
        npm install

    - name: Build
      run: |
        npm run build

    - name: Test
      run: |
        npm run test

  test-mean-squares-versor-registration:
    name: mean-squares-versor-registration
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./examples/mean-squares-versor-registration

    steps:
    - uses: actions/checkout@v3

    - name: 'Free up disk space'
      run: |
        # Workaround for https://github.com/actions/virtual-environments/issues/709
        df -h
        sudo apt-get update
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf /usr/share/dotnet/
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install
      run: |
        npm install

    - name: Build
      run: |
        npm run build

    - name: Build TypeScript/JavaScript bindings
      run: |
        cd typescript
        npm install
        npm run build
