name: JavaScript,TypeScript

on: [push,pull_request]

jobs:
  build-test-deploy:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main

    - name: Pull latest Docker images
      run: |
        ./src/docker/pull.sh

    - uses: actions/setup-node@v3
      with:
        node-version: '18.16'

    - name: Install packages
      run: |
        npm i -g pnpm
        pnpm i

    - name: Build
      run: |
        pnpm run --aggregate-output build

    - name: Lint tests
      run: |
        pnpm run test:lint

    - name: Node tests
      run: |
        pnpm run --aggregate-output test:node

    - name: Browser tests
      run: |
        # Allow writing test/output.html
        sudo chmod 777 test
        # To debug locally, run `./test/run.sh -d`
        ./test/run.sh

    - name: Publish task
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "itk+community@discourse.itk.org"
        # todo: use changeset / pnpm publish
