name: PR Checks
on: pull_request

jobs:
  pr-checks:
    runs-on: ubuntu-22.04
    name: Check and lint PR
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: |
          npm i -g pnpm

      - name: Lint commits
        run: pnpx commitlint --from=${{ github.event.pull_request.base.sha }}
