name: Python Wasm

on: [push,pull_request]

env:
  pyodide-version: 0.24.1

jobs:
  test-itkwasm:
    runs-on: ${{ matrix.os }}
    env:
      python-version: ${{ format('{0}.{1}', matrix.python-major-version, matrix.python-minor-version) }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
        python-major-version: [3]
        python-minor-version: [8, 9, 10, 11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16'
      - name: Install packages
        run: |
          npm i -g pnpm
          pnpm i
      - name: Build
        run: |
          pnpm run --aggregate-output build
      - name: Test on native
        if: ${{ matrix.python-minor-version < 10 }}
        run: |
          pnpm run --aggregate-output test:python:wasi
      - uses: thewtex/pyodide-actions/install-browser@chrome-install
        if: ${{ matrix.python-minor-version > 9 }}
        with:
          runner: selenium
          browser: chrome
          browser-version: latest
      - name: Test with chrome
        if: ${{ matrix.python-minor-version > 9 }}
        run: |
          pnpm run --aggregate-output test:python:emscripten
