name: Toolchains

on: [push,pull_request]

jobs:
  build-itk-wasm-base:
    name: "Build itk-wasm-base"
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: 'Free up disk space'
      run: |
        # Workaround for https://github.com/actions/virtual-environments/issues/709
        df -h
        sudo apt-get update
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf /usr/share/dotnet/
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - name: Pull latest Docker images
      run: |
        ./src/docker/pull.sh

    - uses: actions/download-artifact@v3
      continue-on-error: true
      with:
        name: docker-cache
        path: ./docker-cache

    - name: Build itk-wasm-base
      run: |
        if [[ -e ./docker-cache/itk-wasm-emscripten-base.tar.xz ]]; then xz -d -k < ./docker-cache/itk-wasm-emscripten-base.tar.xz | docker load ; fi
        ./src/docker/itk-wasm-base/build.sh
        mkdir -p ./docker-cache
        docker save itkwasm/emscripten-base:latest | xz -e9 -T0 > ./docker-cache/itk-wasm-emscripten-base.tar.xz

    - name: Build itk-wasm-base
      run: |
        if [[ -e ./docker-cache/itk-wasm-wasi-base.tar.xz ]]; then xz -d -k < ./docker-cache/itk-wasm-wasi-base.tar.xz | docker load ; fi
        ./src/docker/itk-wasm-base/build.sh --with-wasi
        mkdir -p ./docker-cache
        docker save itkwasm/wasi-base:latest | xz -e9 -T0 > ./docker-cache/itk-wasm-wasi-base.tar.xz

    - name: Cache docker results
      uses: actions/upload-artifact@v3
      with:
        name: docker-cache
        path: ./docker-cache
        retention-days: 7

  build-itk-wasm:
    name: "Build itk-wasm"
    needs: build-itk-wasm-base
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: 'Free up disk space'
      run: |
        # Workaround for https://github.com/actions/virtual-environments/issues/709
        df -h
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf /usr/share/dotnet/
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - name: Pull latest Docker images
      run: |
        ./src/docker/pull.sh

    - uses: actions/download-artifact@v3
      continue-on-error: true
      with:
        name: docker-cache
        path: ./docker-cache

    - name: Build itk-wasm
      run: |
        if [[ -e ./docker-cache/itk-wasm-emscripten-base.tar.xz ]]; then xz -d -k < ./docker-cache/itk-wasm-emscripten-base.tar.xz | docker load ; fi
        if [[ -e ./docker-cache/itk-wasm-emscripten.tar.xz ]]; then xz -d -k < ./docker-cache/itk-wasm-emscripten.tar.xz | docker load ; fi
        ./src/docker/itk-wasm/build.sh
        mkdir -p ./docker-cache
        docker save itkwasm/emscripten:latest | xz -e9 -T0 > ./docker-cache/itk-wasm-emscripten.tar.xz

    - name: Build itk-wasi
      run: |
        if [[ -e ./docker-cache/itk-wasm-wasi-base.tar.xz ]]; then xz -d -k < ./docker-cache/itk-wasm-wasi-base.tar.xz | docker load ; fi
        if [[ -e ./docker-cache/itk-wasm-wasi.tar.xz ]]; then xz -d -k < ./docker-cache/itk-wasm-wasi.tar.xz | docker load ; fi
        ./src/docker/itk-wasm/build.sh --with-wasi
        mkdir -p ./docker-cache
        docker save itkwasm/wasi:latest | xz -e9 -T0 > ./docker-cache/itk-wasm-wasi.tar.xz

    - name: Cache docker results
      uses: actions/upload-artifact@v3
      with:
        name: docker-cache
        path: ./docker-cache
        retention-days: 7
