name: WASI

on: [push,pull_request]

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main

    - name: Pull latest Docker images
      run: |
        ./src/docker/pull.sh

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install packages
      run: |
        npm ci

    - name: Build
      run: |
        npm run build:wasi

    - name: Test
      run: |
        npm run test:wasi

    - name: Build WASI packages
      run: |
        npm run build:wasi:packages
